//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VillaOy.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Logins
    {
        public string LoginId { get; set; }
        [DisplayName("K‰ytt‰j‰")]
        [Required(ErrorMessage="T‰m‰ kentt‰ pit‰‰ t‰ytt‰‰.")]
        public string UserName { get; set; }
        [DataType(DataType.Password)]
        [DisplayName("Salasana")]
        [Required(ErrorMessage = "T‰m‰ kentt‰ pit‰‰ t‰ytt‰‰.")]
        public string PassWord { get; set; }
        public string ErrorMessage { get; set; }
    }
}
